services:

  mysql:
    image: mysql:8.0

    container_name: mysql

    environment:
      MYSQL_ROOT_PASSWORD: root123
      MYSQL_DATABASE: course_reg_sys

    ports:
      - "3307:3306"

  backend:
    build: .

    container_name: backend

    ports:
      - "8080:8080"

    depends_on:
      - mysql
      - restart: always